name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: lucascraftech/cicd-academy:${{ github.sha }}

  docker-run:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    name: Docker run
    steps:
      - run: docker run lucascraftech/cicd-academy:${{ github.sha }}