name: ci

on:
  push:
    branches:
      - 'stg'
      - 'dev'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: lucascraftech/cicd-academy:${{ github.sha }},lucascraftech/cicd-academy:${{ github.ref_name }}-${{ github.run_id }}

  docker-run-dev:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/dev')
    name: Docker run dev
    steps:
      - run: docker run -e BRANCH=dev lucascraftech/cicd-academy:dev-${{ github.run_id }}

  docker-run-stg:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/stg')
    name: Docker run stg
    steps:
      - run: docker run -e BRANCH=stg lucascraftech/cicd-academy:stg-${{ github.run_id }}